@startuml

!theme plain

Browser -> Portal : Login Page
Browser <- Portal : Redirect to authorization server
Browser -> "Authorization Server" : Authorization code request to /authorize
Browser <- "Authorization Server" : Redirect to authentication prompt
Browser -> "Authorization Server" : Authentication and consent
Browser <- "Authorization Server" : Redirect to callback page
Browser -> Portal : Forward authorization code in URL
Portal -> "Authorization Server" : Send authorization code and client secret to /token
Portal <- "Authorization Server" : Access token (JWT)
Browser <- Portal : Redirect to portal page with JWT in set cookie
Browser -> Portal : Request with access token (JWT) in cookie
Portal -> Portal: Locally validates JWT token
Browser <- Portal : Response
Browser -> Broker : Request with access token (JWT) in cookie
Broker -> Broker: Locally validates JWT token
Broker -> Device : Request
Broker <- Device : Response
Browser <- Broker : Response


@enduml
