# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-12-11T17:49:50Z"
  labels:
    app: oauthtut
  name: oauthtut
spec:
  containers:
  - image: localhost/portal:latest
    name: portal
    envFrom:
    - configMapRef:
        name: portal
        optional: false
    ports:
    - containerPort: 8080
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  - image: localhost/broker:latest
    name: broker
    envFrom:
    - configMapRef:
        name: broker
        optional: false
    ports:
    - containerPort: 8888
      hostPort: 8888
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  - image: localhost/device:latest
    name: device
    ports:
    - containerPort: 8000
      hostPort: 8000
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  restartPolicy: Never
status: {}

